Starting backend setup and first endpoint
manuelamercado/exercise-tracker pull request #1
Opened 2021-03-29 16:25 UTC by manuelamercado

2021-03-29 20:19 UTC, jpolanco91 requested changes
-Comment the unused `SECRET_KEY` config.
-Verify why do we have a `true` value in `Access-Control-Allow-Headers`
-Investigate about PEP8 and make the code compliant with it.
-Complete the GET endpoint for users (using log and userId query params).
-Make the GET/POST endpoints for exercises.

2021-03-29 20:19 UTC, jpolanco91 commented on backend/models.py
> +  id = Column(Integer, primary_key=True)
TODO: Use hash for this key. If not hash type found save the hash as string or char

2021-03-29 20:19 UTC, jpolanco91 commented on backend/config.py
> +SECRET_KEY = os.urandom(32)
Let's check this to see if it's used

2021-03-29 20:19 UTC, jpolanco91 commented on backend/api.py
> +    response.headers.add('Access-Control-Allow-Headers', 'Content-Type,Authorization,true')
What's the `true` value for in `Access-Control-Allow-Headers`

2021-03-31 14:25 UTC, manuelamercado commented on backend/models.py
> +  id = Column(Integer, primary_key=True)
Postgres has a type called UUID. The only difference is that it adds some `-`.

2021-03-31 15:00 UTC, manuelamercado commented on backend/config.py
> +SECRET_KEY = os.urandom(32)
This is for signing the session cookies. In this way the secret is reset every time the app start, so all the users will lose the sessions if the server is restarted.

2021-03-31 15:38 UTC, manuelamercado commented on backend/api.py
> +    response.headers.add('Access-Control-Allow-Headers', 'Content-Type,Authorization,true')
This is the value to accept the `Access-Control-Allow-Headers`

2021-04-01 18:38 UTC, jpolanco91 requested changes
Looking good so far, only to fix some little styling and code feedbacks

2021-04-01 18:38 UTC, jpolanco91 commented on backend/app.py
> +    POST /api/exercise/add
Quoted comments should be starting at the first line of the function

2021-04-01 18:38 UTC, jpolanco91 commented on backend/app.py
> +    returns a json {'count': count} where count is the number of exercises
Same here. Move this to the first line of the function's body.

2021-04-01 18:38 UTC, jpolanco91 commented on backend/app.py
> +                          Exercise.exercise_date <= to_date
Duplicated line of code

2021-04-01 18:38 UTC, jpolanco91 commented on backend/app.py
> +                          Exercise.exercise_date <= to_date
Same as before, duplicated line of code

2021-04-01 18:38 UTC, jpolanco91 commented on backend/app.py
> +                if len(exercises_data):
Should check if it's not equal to 0 using `!=`

2021-04-01 18:38 UTC, jpolanco91 commented on backend/app.py
> +                    abort(404)
Should return an empty object. 404 errors are exclusive for when an endpoint/route/page does not exist.

2021-04-01 18:50 UTC, jpolanco91 commented
Also for the next session, investigate how to simplify the the `from_date` and `to_date` logic.

2021-04-06 21:34 UTC, jpolanco91 submitted a review, later dismissed
LGTM !! merge it !!

2021-04-06 21:35 UTC, merged